apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcs-postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/pcs/postgres/data"
  capacity:
    storage: 50Gi
