apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcs-public-pv
  labels:
    type: local
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/pcs/public"
  capacity:
    storage: 50Gi
