apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pcs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/pcs/api-pcs/public"
  capacity:
    storage: 50Gi
