apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pcs-pvc
  labels:
    app: pcs
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi