apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcs-public-pvc
  labels:
    app: pcs
spec:
  storageClassName: manual
  # volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi