apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pcs
resources:
- ../../base
# ---
# patches:
# - patch: |-
#     [
#       {"op": "replace", "path": "/spec/minReplicas", "value": 1},
#       {"op": "replace", "path": "/spec/maxReplicas", "value": 10}
#     ]
#   target:
#     kind: HorizontalPodAutoscaler
# ---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- literals:
  - NODE_ENV="production"
  - DOMAIN="bleme.fr"
  - DATABASE_URL="postgresql://pcs:pcs@postgres.pcs.svc.cluster.local:5432/pcs?schema=public"
  - API_STRIPE="http://api-stripe.pcs.svc.cluster.local"
  - COOKIE_NAME="token"
  - JWT_SECRET="MY_SECRET"
  - PORT="80"
  name: api-pcs-env
- files:
  - files/config/production.yaml
  name: api-pcs-config
