apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pcs
resources:
- ../../base
# ---
patches:
- patch: |-
    [
      {"op": "replace", "path": "/spec/minReplicas", "value": 1},
      {"op": "replace", "path": "/spec/maxReplicas", "value": 3}
    ]
  target:
    kind: HorizontalPodAutoscaler
# ---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: front-pcs-env
  files:
  - files/config/env.js
