apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pcs
resources:
- ../../base
# ---
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: pcs-postgres-env
  literals:
  - NODE_ENV="production"
  - POSTGRES_DB="pcs"
  - POSTGRES_USER="pcs"
  - POSTGRES_PASSWORD="pcs"
  - PGDATA="/var/lib/postgresql/data/pgdata"
  